"""Initial tables

Revision ID: 461ed98861f6
Revises: 
Create Date: 2026-06-09 15:57:00.345780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461ed98861f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('resume_path', sa.String(length=255), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    
    # Bulk insert default projects (seeding) with fm=webp format
    projects_table = sa.table('projects',
        sa.column('id', sa.Integer),
        sa.column('title', sa.String),
        sa.column('description', sa.Text),
        sa.column('image_url', sa.String),
        sa.column('tech_stack', sa.String),
        sa.column('github_url', sa.String),
        sa.column('live_url', sa.String)
    )
    op.bulk_insert(projects_table, [
        {
            "id": 1,
            "title": "Aura Fintech Portal",
            "description": "A secure glassmorphic financial transaction platform showcasing real-time analytics, instant multi-currency transfers, and AI-driven spending patterns. Built with security and scalability as core architectural constraints.",
            "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop&fm=webp",
            "tech_stack": "React, Tailwind CSS, FastAPI, PostgreSQL, AWS",
            "github_url": "/placeholder.html",
            "live_url": "/placeholder.html"
        },
        {
            "id": 2,
            "title": "Vortex AI Dashboard",
            "description": "An enterprise-grade orchestration pipeline for LLM deployments. Features multi-agent collaboration interfaces, fine-tuning task management, and visual analytics for token consumption metrics.",
            "image_url": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=800&auto=format&fit=crop&fm=webp",
            "tech_stack": "FastAPI, Python, React, Tailwind, Framer Motion",
            "github_url": "/placeholder.html",
            "live_url": "/placeholder.html"
        },
        {
            "id": 3,
            "title": "Helios Cloud Infrastructure",
            "description": "Automated multi-cloud infrastructure provisioner and scaling monitor. Streamlines Kubernetes cluster setups, AWS/GCP resource alignment, and provides high-performance logging streams.",
            "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop&fm=webp",
            "tech_stack": "Docker, FastAPI, PostgreSQL, Kubernetes, AWS",
            "github_url": "/placeholder.html",
            "live_url": "/placeholder.html"
        }
    ])
    
    # Bulk insert default jobs (seeding)
    jobs_table = sa.table('jobs',
        sa.column('id', sa.Integer),
        sa.column('title', sa.String),
        sa.column('location', sa.String),
        sa.column('experience', sa.String),
        sa.column('employment_type', sa.String),
        sa.column('description', sa.Text)
    )
    op.bulk_insert(jobs_table, [
        {
            "id": 1,
            "title": "Senior React Developer",
            "location": "Remote (USA / Europe / Asia)",
            "experience": "5+ Years",
            "employment_type": "Full-Time",
            "description": "### Role Overview\nVeila Technologies is looking for a Senior React Developer to join our core product team. You will lead the frontend architecture, designing modular components and implementing interactive, smooth UI/UX with high animation fidelity.\n\n### Requirements\n- Strong experience in React.js, Tailwind CSS, and state management.\n- Hands-on experience with Framer Motion, GSAP, or general animation principles.\n- Familiarity with RESTful APIs, Axios integration, and performance benchmarking."
        },
        {
            "id": 2,
            "title": "Full Stack Software Engineer",
            "location": "Hybrid (New York, NY)",
            "experience": "3+ Years",
            "employment_type": "Full-Time",
            "description": "### Role Overview\nWe are looking for a versatile Full Stack Developer to build high-performance web applications. You will work on both our FastAPI microservices and React dashboards, managing database schemas, integrations, and server deployments.\n\n### Requirements\n- Experience with Python (FastAPI, Flask or Django) and relational databases (PostgreSQL/SQLAlchemy).\n- Experience with React, modern state libraries, and responsive web design.\n- Solid knowledge of containerization (Docker) and Git workflows."
        },
        {
            "id": 3,
            "title": "DevOps & Security Architect",
            "location": "Remote",
            "experience": "6+ Years",
            "employment_type": "Contract",
            "description": "### Role Overview\nManage our scalable cloud deployments, security policies, and continuous integration pipelines. You will orchestrate containerized services and ensure high reliability, fast load speeds, and enterprise security compliance.\n\n### Requirements\n- Deep experience with AWS cloud infrastructure (VPC, EC2, ECS, RDS, S3).\n- Mastery of Docker, CI/CD tools (GitHub Actions, GitLab CI), and Terraform.\n- Strong understanding of web security, SSL, JWT authentication, and DDOS mitigation."
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
